sbrunner/vim:latest:
  debian_13/adduser: '3.152'
  debian_13/apt: 3.0.3
  debian_13/base-passwd: 3.6.7
  debian_13/bash: 5.2.37-2+b5
  debian_13/bsdutils: 1:2.41-5
  debian_13/ca-certificates: '20250419'
  debian_13/containerd: 1.7.24~ds1-6+b4
  debian_13/coreutils: 9.7-3
  debian_13/cron: 3.0pl1-197
  debian_13/cron-daemon-common: 3.0pl1-197
  debian_13/dash: 0.5.12-12
  debian_13/debconf: 1.5.91
  debian_13/debian-archive-keyring: '2025.1'
  debian_13/debianutils: 5.23.2
  debian_13/diffutils: 1:3.10-4
  debian_13/docker.io: 26.1.5+dfsg1-9+b9
  debian_13/dpkg: 1.22.21
  debian_13/fdupes: 1:2.3.2-1
  debian_13/findutils: 4.10.0-3
  debian_13/gcc-14-base: 14.2.0-19
  debian_13/git: 1:2.47.3-0+deb13u1
  debian_13/git-man: 1:2.47.3-0+deb13u1
  debian_13/grep: 3.11-4
  debian_13/gzip: 1.13-1
  debian_13/hostname: '3.25'
  debian_13/init-system-helpers: 1.69~deb13u1
  debian_13/iptables: 1.8.11-2
  debian_13/iputils-ping: 3:20240905-3
  debian_13/less: 668-1
  debian_13/libacl1: 2.3.2-2+b1
  debian_13/libapparmor1: 4.1.0-1
  debian_13/libapt-pkg7.0: 3.0.3
  debian_13/libattr1: 1:2.5.2-3
  debian_13/libaudit-common: 1:4.0.2-2
  debian_13/libaudit1: 1:4.0.2-2+b2
  debian_13/libblkid1: 2.41-5
  debian_13/libbrotli1: 1.1.0-2+b7
  debian_13/libbsd0: 0.12.2-2
  debian_13/libbz2-1.0: 1.0.8-6
  debian_13/libc-bin: 2.41-12
  debian_13/libc6: 2.41-12
  debian_13/libcap-ng0: 0.8.5-4+b1
  debian_13/libcap2: 1:2.75-10+b1
  debian_13/libcom-err2: 1.47.2-3+b3
  debian_13/libcrypt1: 1:4.4.38-1
  debian_13/libcurl3t64-gnutls: 8.14.1-2
  debian_13/libdb5.3t64: 5.3.28+dfsg2-9
  debian_13/libdebconfclient0: '0.280'
  debian_13/liberror-perl: 0.17030-1
  debian_13/libexpat1: 2.7.1-2
  debian_13/libffi8: 3.4.8-2
  debian_13/libgcc-s1: 14.2.0-19
  debian_13/libgdbm-compat4t64: 1.24-2
  debian_13/libgdbm6t64: 1.24-2
  debian_13/libgmp10: 2:6.3.0+dfsg-3
  debian_13/libgnutls30t64: 3.8.9-3
  debian_13/libgpm2: 1.20.7-11+b2
  debian_13/libgssapi-krb5-2: 1.21.3-5
  debian_13/libhogweed6t64: 3.10.1-1
  debian_13/libidn2-0: 2.3.8-2
  debian_13/libip4tc2: 1.8.11-2
  debian_13/libip6tc2: 1.8.11-2
  debian_13/libk5crypto3: 1.21.3-5
  debian_13/libkeyutils1: 1.6.3-6
  debian_13/libkrb5-3: 1.21.3-5
  debian_13/libkrb5support0: 1.21.3-5
  debian_13/liblastlog2-2: 2.41-5
  debian_13/libldap2: 2.6.10+dfsg-1
  debian_13/liblz4-1: 1.10.0-4
  debian_13/liblzma5: 5.8.1-1
  debian_13/libmd0: 1.1.0-2+b1
  debian_13/libmnl0: 1.0.5-3
  debian_13/libmount1: 2.41-5
  debian_13/libncursesw6: 6.5+20250216-2
  debian_13/libnetfilter-conntrack3: 1.1.0-1
  debian_13/libnettle8t64: 3.10.1-1
  debian_13/libnfnetlink0: 1.0.2-3
  debian_13/libnftnl11: 1.2.9-1
  debian_13/libnghttp2-14: 1.64.0-1.1
  debian_13/libnghttp3-9: 1.8.0-1
  debian_13/libngtcp2-16: 1.11.0-1
  debian_13/libngtcp2-crypto-gnutls8: 1.11.0-1
  debian_13/libp11-kit0: 0.25.5-3
  debian_13/libpam-modules: 1.7.0-5
  debian_13/libpam-modules-bin: 1.7.0-5
  debian_13/libpam-runtime: 1.7.0-5
  debian_13/libpam0g: 1.7.0-5
  debian_13/libpcre2-32-0: 10.46-1~deb13u1
  debian_13/libpcre2-8-0: 10.46-1~deb13u1
  debian_13/libperl5.40: 5.40.1-6
  debian_13/libpopt0: 1.19+dfsg-2
  debian_13/libproc2-0: 2:4.0.4-9
  debian_13/libpsl5t64: 0.21.2-1.1+b1
  debian_13/libpython3-stdlib: 3.13.5-1
  debian_13/libpython3.13-minimal: 3.13.5-2
  debian_13/libpython3.13-stdlib: 3.13.5-2
  debian_13/libreadline8t64: 8.2-6
  debian_13/librtmp1: 2.4+20151223.gitfa8646d.1-2+b5
  debian_13/libsasl2-2: 2.1.28+dfsg1-9
  debian_13/libsasl2-modules-db: 2.1.28+dfsg1-9
  debian_13/libseccomp2: 2.6.0-2
  debian_13/libselinux1: 3.8.1-1
  debian_13/libsemanage-common: 3.8.1-1
  debian_13/libsemanage2: 3.8.1-1
  debian_13/libsepol2: 3.8.1-1
  debian_13/libsmartcols1: 2.41-5
  debian_13/libsodium23: 1.0.18-1+b2
  debian_13/libsqlite3-0: 3.46.1-7
  debian_13/libssh2-1t64: 1.11.1-1
  debian_13/libssl3t64: 3.5.1-1+deb13u1
  debian_13/libstdc++6: 14.2.0-19
  debian_13/libsystemd-shared: 257.8-1~deb13u2
  debian_13/libsystemd0: 257.8-1~deb13u2
  debian_13/libtasn1-6: 4.20.0-2
  debian_13/libtinfo6: 6.5+20250216-2
  debian_13/libudev1: 257.8-1~deb13u2
  debian_13/libunistring5: 1.3-2
  debian_13/libuuid1: 2.41-5
  debian_13/libxtables12: 1.8.11-2
  debian_13/libxxhash0: 0.8.3-2
  debian_13/libzstd1: 1.5.7+dfsg-1
  debian_13/login: 1:4.16.0-2+really2.41-5
  debian_13/login.defs: 1:4.17.4-2
  debian_13/mawk: 1.3.4.20250131-1
  debian_13/media-types: 13.0.0
  debian_13/mount: 2.41-5
  debian_13/ncurses-base: 6.5+20250216-2
  debian_13/ncurses-bin: 6.5+20250216-2
  debian_13/net-tools: 2.10-1.3
  debian_13/netbase: '6.5'
  debian_13/openssl: 3.5.1-1+deb13u1
  debian_13/openssl-provider-legacy: 3.5.1-1+deb13u1
  debian_13/passwd: 1:4.17.4-2
  debian_13/perl: 5.40.1-6
  debian_13/perl-base: 5.40.1-6
  debian_13/perl-modules-5.40: 5.40.1-6
  debian_13/procps: 2:4.0.4-9
  debian_13/python-is-python3: 3.13.3-1
  debian_13/python3: 3.13.5-1
  debian_13/python3-minimal: 3.13.5-1
  debian_13/python3-packaging: 25.0-1
  debian_13/python3-pip: 25.1.1+dfsg-1
  debian_13/python3-wheel: 0.46.1-2
  debian_13/python3.13: 3.13.5-2
  debian_13/python3.13-minimal: 3.13.5-2
  debian_13/readline-common: 8.2-6
  debian_13/rsync: 3.4.1+ds1-5
  debian_13/runc: 1.1.15+ds1-2+b4
  debian_13/screen: 4.9.1-3
  debian_13/sed: 4.9-2
  debian_13/sensible-utils: 0.0.25
  debian_13/sqv: 1.3.0-3
  debian_13/systemd: 257.8-1~deb13u2
  debian_13/sysvinit-utils: 3.14-4
  debian_13/tar: 1.35+dfsg-3.1
  debian_13/tini: 0.19.0-3+b3
  debian_13/tree: 2.2.1-1
  debian_13/tzdata: 2025b-4+deb13u1
  debian_13/util-linux: 2.41-5
  debian_13/vim: 2:9.1.1230-2
  debian_13/vim-common: 2:9.1.1230-2
  debian_13/vim-runtime: 2:9.1.1230-2
