# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/tag-publish/0.13.0/tag_publish/schema.json

docker:
  images:
    - name: sbrunner/vim
print_versions:
  versions:
    - name: c2cciutils
      cmd:
        - c2cciutils
        - --version
    - name: python
      cmd:
        - python3
        - --version
    - name: twine
      cmd:
        - twine
        - --version
    - name: docker
      cmd:
        - docker
        - --version
dispatch:
  - {}
