[tool.black]
line-length = 110
target-version = ["py39"]

[tool.poetry]
name = "docker-vim"
version = "0.0.0"
description = "Docker image with vim and other tools."
authors = ["Stéphane Brunner <stephane.brunner@gmail.com>"]
