checks:
  versions: False
  required_workflows:
    backport.yaml: False
    clean.yaml: False
    audit.yaml: False
    codeql.yaml: False
publish:
  pypi:
    packages: []
  images:
    - name: sbrunner/vim
