checks:
  versions: False
  required_workflows:
    backport.yaml: False
    audit.yaml: False
    codeql.yaml: False
publish:
  pypi:
    packages: []
  docker:
    images:
      - name: sbrunner/vim
