# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/1.7.1/c2cciutils/schema.json

publish:
  pypi:
    packages: []
  docker:
    images:
      - name: sbrunner/vim
    repository:
      github: {}
    dispatch: false
