---
name: Clean docker hub tags

on: delete

jobs:
  clean:
    runs-on: ubuntu-20.04
    name: Clean docker hub tags
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --requirement=ci/requirements.txt

      - name: Clean Docker hub tags
        run: c2cciutils-clean
        env:
          DOCKERHUB_USERNAME: sbrunner
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
